validaçao, toast e input de data criados, e checkbox removido
zanniboni/greeny-time-app pull request #10
Opened 2023-04-04 18:53 UTC by lzn1996

validaçao para nao permitir numeros negativos, feedback com toast e botao readonly da data e hora criado, e removido checkbox sem uso

2023-04-04 23:59 UTC, zanniboni commented
> validaçao para nao permitir numeros negativos, feedback com toast e botao readonly da data e hora criado, e removido checkbox sem uso

Tenta organizar em lista dps, ex:

> validaçao para nao permitir numeros negativos, 
> feedback com toast e botao readonly da data e hora criado
> removido checkbox sem uso

2023-04-05 14:25 UTC, lzn1996 commented
ok

2023-04-05 14:49 UTC, zanniboni requested changes

2023-04-05 14:49 UTC, zanniboni commented on src/components/WorkHours/AddWorkHours/AddWorkHoursForm.jsx
> +  const isValidPositiveNumber = (value) => {
Eu acho que a gnt pode extrair esse método isValidPositiveNumber para um novo arquivo dentro de uma pasta chamada "Validators", e importa-lo nos arquivos que vamos precisa usa-lo

2023-04-05 14:49 UTC, zanniboni commented on src/components/WorkHours/AddWorkHours/DateReadOnlyInput.jsx
> +      setCurrentDate(moment().tz("America/Sao_Paulo").format("DD/MM/YYYY HH:mm"));
`"DD/MM/YYYY HH:mm"`  -> pode se transformar numa const e ser reaproveitado no código

2023-04-05 14:49 UTC, zanniboni commented on src/components/WorkHours/AddWorkHours/DateReadOnlyInput.jsx
> +      setCurrentDate(moment().tz("America/Sao_Paulo").format("DD/MM/YYYY HH:mm"));
`"America/Sao_Paulo"` -> pode se transformar numa const e ser reaproveitado no código

2023-04-05 14:49 UTC, zanniboni commented on src/components/WorkHours/AddWorkHours/AddWorkHoursForm.jsx
> +        <DateReadOnlyInput />
Esse componente faz parte da `Home` da página `AddWorkHoursForm`, deveria estar no arquivo `Home.jsx`

2023-04-05 23:50 UTC, zanniboni approved these changes

2023-04-05 23:50 UTC, merged