datapicker adicionado, criaçao de componente formulario e separaçao d…
zanniboni/greeny-time-app pull request #11
Opened 2023-04-06 20:06 UTC by lzn1996

criado de componente datapicker,
adicionado no home de salarios,
criação/separação de  componente formulario para repetir em outras telas e adicionado nos Home,
separação de componente DateInput para reutilização

2023-04-08 17:40 UTC, zanniboni requested changes

2023-04-08 17:40 UTC, zanniboni commented on package.json
> +    "@react-native-community/datetimepicker": "^6.7.3",
Será que a versão community é realmente segura? Consegue fazer esse checke?

2023-04-08 17:40 UTC, zanniboni commented on package.json
> +    "react-native-modern-datepicker": "^1.0.0-beta.91",
Tem vários date-pickers no projeto, a gnt precisa de todos?

2023-04-08 17:40 UTC, zanniboni commented on src/components/Calendar/Calendar.jsx
> +  const [open, setOpen] = useState(false); //abre e fecha o modal
Remove o comentário da linha pfv

2023-04-08 17:40 UTC, zanniboni commented on src/components/Salary/Home.jsx
> +      <Formulary title={'Salário bruto'} placeholder={'10.000'} />
Sugestão:
placeholder={'R$ 10.000,00'}

2023-04-08 17:40 UTC, zanniboni commented on src/components/Validators/IsValidPositiveNumbers.jsx
>      const regex = /^[0-9,.]+$/; // regex para números, vírgulas e pontos
remove os comentários

2023-04-08 17:40 UTC, zanniboni commented on yarn.lock
Não precisa comentar o yarn.lock, adiciona ele no .gitignore

2023-04-09 02:19 UTC, lzn1996 commented on package.json
> +    "@react-native-community/datetimepicker": "^6.7.3",
Tive que testar alguns e acabei esquecendo de tirar, esse da community nao ta sendo usado no projeto, só o modern datepicker, vou tirar os inuteis

2023-04-09 02:22 UTC, lzn1996 commented on package.json
> +    "react-native-modern-datepicker": "^1.0.0-beta.91",
deixei só o modern

2023-04-09 02:22 UTC, lzn1996 commented on src/components/Calendar/Calendar.jsx
> +  const [open, setOpen] = useState(false); //abre e fecha o modal
ok

2023-04-09 02:22 UTC, lzn1996 commented on src/components/Salary/Home.jsx
> +      <Formulary title={'Salário bruto'} placeholder={'10.000'} />
ok

2023-04-09 02:22 UTC, lzn1996 commented on src/components/Validators/IsValidPositiveNumbers.jsx
>      const regex = /^[0-9,.]+$/; // regex para números, vírgulas e pontos
ok

2023-04-09 02:25 UTC, lzn1996 commented on yarn.lock
adicionei la no gitignore, mas n tinha mexido nele antes, se mexi nem vi

2023-04-09 15:59 UTC, zanniboni requested changes

2023-04-09 15:59 UTC, zanniboni commented on App.jsx
> +        <Stack.Screen name="RegisterSalary" component={RegisterSalaryScreen} options={{headerTitleAlign: 'center'}} />
Muda pra português o RegisterSalary

2023-04-09 15:59 UTC, zanniboni commented on App.jsx
> +        <Stack.Screen name="Bem vindo" component={WelcomeScreen} options={{headerTitleAlign: 'center'}}/>
options={{headerTitleAlign: 'center'}}

Isso pode virar um constante, pra evitar repetição

2023-04-09 15:59 UTC, zanniboni commented on src/components/Login/Login.jsx
> +              {`Bem-vindo(a)! Por favor, faça login para continuar.`}
Acho que não precisa usar template string aqui

2023-04-09 15:59 UTC, zanniboni commented on App.jsx
> +import WelcomeScreen from "./src/components/WelcomeScreen/WelcomeScreen";
Mano, o nome do componente é WelcomeScreen, porém o nome do arquivo .jsx deveria ser "Home"

2023-04-09 15:59 UTC, zanniboni commented on src/components/WelcomeScreen/WelcomeScreen.jsx
O nome do arquivo deveria ser Home.jsx

2023-04-09 19:01 UTC, lzn1996 commented
ok

2023-04-10 23:36 UTC, merged